basics:
  debug: false
  prefix: "&8[&bAbs01uteMagicBullet&8] &r"

language:
  default: "zh_cn"
  fallback: "en_us"

features:
  magic-bullet:
    enabled: true
  command-bullet:
    enabled: true
    log-commands: false
    max-command-executions: 500